### ISSUE TITLE
Code fails to run due to local absolute paths/directories references

### ISSUE THREAD

**Issue by smonami** [dataloop-ai/ZazuML-easy_AutoML#16]
See attached image, there are places where local path is hardcoded. Refactor code to generalize.

![Screen Shot 2020-09-08 at 4 33 22 PM](https://user-images.githubusercontent.com/1485640/92530125-627d1b80-f1f1-11ea-87e4-08a3e8e344f2.png)

**Comment by NoamRosenberg** [comment]
@smonami Sorry about this, not all the original functions in this code are functional and the repo still has to be cleaned up quite a bit. However for now, -- search should work just fine.
