### ISSUE TITLE
hypermeter search

### ISSUE THREAD

**Issue by LianShuaiLong** [dataloop-ai/ZazuML-easy_AutoML#18]
hi,first of all,you have done an interesting work;however, i has some questions about ZazuML,i wonder if there anyway for hypermeter seach only? or how can i do hypermeter search only?

**Comment by NoamRosenberg** [comment]
@LianShuaiLong For now, you can add your network to the networks package in this project, and configure it with the object detection package. However, there is work to do to make this easier, and though this was not the original intention of the project, I really want this functionality.  If you'd like to work on making this process easier, such that anyone could easily add their own model, your contribution would be very valuable to the project. Hope to hear from you soon!
